spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie
    username: postgres
    password: tawkenskiy
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: tawkenskiy000@gmail.com
    password: tbeg euqe tnao ajfe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



  aws:
    s3:
      bucket-name: sharipovi
      region: us-east-2
      access-key: AKIA2YJH2KGCN7ZUD6LV
      secret-key: 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
